[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy-Report-Only = "default-src 'self'; fonr-src fonts.gstatic.com; frame-src *.twitter.com *.instagram.com *.youtube.com *.alu.jp report-uri https://ikarugaorg.report-uri.com/r/d/csp/reportOnly"

