name: "test"

on:
  issues:
    types: [labeled]

jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test
          column: TODO
          repo-token: ${{ secrets.GITHUB_TOKEN }}
